### ISSUE TITLE
Heads up: NPE with JDK15

### ISSUE THREAD

**Issue by danielsz** [clojure-emacs/orchard#100]
With JDK15, the Standard Doclet no longer generates pre-compressed index files. 

This [line](https://github.com/clojure-emacs/orchard/blob/08aa046d7882a91d698043265f651877bc333e6e/src/orchard/java/parser.clj#L77) generates a NPE with JDK15.

```java
java.lang.NullPointerException: Cannot invoke "jdk.javadoc.internal.doclets.formats.html.HtmlConfiguration.getOptions()" because "this.configuration" is null
        at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDoclet.getSupportedOptions(HtmlDoclet.java:292)
        at jdk.javadoc/jdk.javadoc.doclet.StandardDoclet.getSupportedOptions(StandardDoclet.java:93)
        at cider.nrepl.inlined_deps.orchard.v0v6v0.orchard.java.parser$parse_java$reify__12158.getSupportedOptions(parser.clj:77) 
```

**Comment by bbatsov** [comment]
Thanks for the heads up! Seems that every JDK breaks something with respect to our Java parser. 😢

**Comment by davidiba** [comment]
Updating all emacs packages fixed this issue for me.

**Comment by bpringe** [comment]
Just had a Calva user report this issue when used in a `lein new` project with OpenJDK 15.

**Comment by bbatsov** [comment]
Not sure how to best approach this, though. @jeffvalk Any suggestions?

**Comment by jeffvalk** [comment]
This is a good heads up. Thanks, @danielsz.

> Seems that every JDK breaks something with respect to our Java parser.

We did have that liability with the original Java parser (now `legacy.parser.clj`), as it relied on internal APIs. When it was written, that was the only available option.

The current `parser.clj`, though, was rewritten to support JDK 9+ and uses only public APIs. Its behavior should be as stable as those APIs. Maybe there's an edge case in our use of the APIs; but if not, and a new JDK release breaks the Java parser, this would _technically_ be the JDK breaking compatibility in a supported API, which is either a big deal or a JDK bug.

In this case, I'm not sure which we're dealing with. The issue @danielsz noted is [JDK-8237909](
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8237909). I think the first thing to do is identify what may have changed underneath the methods we call. The commit associated with that JDK issue is [here](https://github.com/openjdk/jdk/commit/56a76315553baff0bf5e1fdeccbdec5e3b1f3265). Insights from anyone who has time to take a look would be appreciated!

**Comment by jeffvalk** [comment]
Would someone running JDK15 please execute the following in a REPL and post the result:

```clj
(count (.getSupportedOptions (jdk.javadoc.doclet.StandardDoclet.)))
```

**Comment by dharrigan** [comment]
On 01/01/2021 22:48:13, Jeff Valk wrote:

> Would someone running JDK15 please execute the following in a REPL and post the result:
>
> ```clj
> (count (.getSupportedOptions (jdk.javadoc.doclet.StandardDoclet.)))
> ```

Hi,

```
❯ java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```

```
user=> (count (.getSupportedOptions (jdk.javadoc.doclet.StandardDoclet.)))
Execution error (NullPointerException) at jdk.javadoc.internal.doclets.formats.html.HtmlDoclet/getSupportedOptions (HtmlDoclet.java:292).
Cannot invoke "jdk.javadoc.internal.doclets.formats.html.HtmlConfiguration.getOptions()" because "this.configuration" is null
```

I prefer encrypted and signed messages.
GPG Fingerprint: 110AF423364754E2880FADAD1C5285BFB20A22F9

No trees were harmed in the sending of this message, however, a number
of electrons were inconvenienced.

This email is sent without prejudice.

**Comment by jeffvalk** [comment]
Thanks, @dharrigan . Does the following get rid of the error?

```clj
(count (.getSupportedOptions (doto (jdk.javadoc.doclet.StandardDoclet.)
                               (.init (java.util.Locale/getDefault) nil))))
```

**Comment by dharrigan** [comment]
Hi,

Yes :-)

```
❯ clj
nREPL client can be connected to port 34485
[Rebel readline] Type :repl/help for online help info
user=> (count (.getSupportedOptions (doto (jdk.javadoc.doclet.StandardDoclet.)
  #_=>                                (.init (java.util.Locale/getDefault) nil))))
  #_=> 
55
```

**Comment by jeffvalk** [comment]
Ok, here is the forensic analysis: 

- The offending JDK commit is [this one][commit]. This change moves initialization of a private `configuration` object used by the internal `jdk.javadoc.internal.doclets.formats.html.HtmlDoclet` class from the constructor to the `init()` method. No mention of this change is made in the commit message or the release notes.
- The commit is related to [JDK-8222793][issue], rather than the pre-compressed index file issue.

For our purposes, this can be solved for by calling `init()` on the `StandardDoclet` object as illustrated above. But I think the better solution is to remove the reference to `StandardDoclet` and have the reified `getSupportedOptions` method return the empty set. The latter is more accurate, and it would reduce the overall code path inside the JDK compiler classes, and therefore our exposure to future breakage. :roll_eyes:

I'll push a fix shortly.

[issue]: https://bugs.openjdk.java.net/browse/JDK-8222793
[commit]: https://github.com/openjdk/jdk/commit/98f5d98a8826800a5ea25d796977f4a558426e3c

**Comment by bbatsov** [comment]
Thanks for looking into this! 🙇‍♂️

**Comment by jeffvalk** [comment]
@bbatsov The CI configuration currently tests against JDK8 and 11. Could we add JDK15 to this?

It might be good policy for CI tests to run against the current JDK release, plus all currently supported LTS releases.

**Comment by bbatsov** [comment]
Yeah, that's a good idea. Technically speak, this was supposed to be our policy https://docs.cider.mx/cider/1.0/about/compatibility.html#java Seems we forgot about this.

**Comment by danielsz** [comment]
Awesome work, @jeffvalk. Thank you.

> Ok, here is the forensic analysis:
> I'll push a fix shortly.
