### ISSUE TITLE
Flaky unit test

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/orchard#104]
I've noticed that from time to time we get the following test failure https://app.circleci.com/pipelines/github/clojure-emacs/orchard/248/workflows/bcb49435-2c56-44f3-ad19-78d3bde2715b/jobs/2124

I guess we should investigate this at some point.

**Comment by vemv** [comment]
This one is precisely the one I got to hunt down in https://github.com/clojure-emacs/orchard/commit/a233ee6867ee30f769c9a0526cca10efb1508cb6

**Comment by bbatsov** [comment]
Great!
