### ISSUE TITLE
info op fails for cljs macro in aliased namespace

### ISSUE THREAD

**Issue by jobo3208** [clojure-emacs/orchard#106]
## Expected behavior

```clojure
(ns my-ns.core
  (:require
    [cljs.spec.alpha :as s]))
```

Given this `ns`, when I do an info op on `s/keys` (a macro), it should return the macro metadata.

## Actual behavior

Instead, it returns nil. The info op works fine for functions like `s/explain`. It also works fine if I `:refer` the macro explicitly.

## Steps to reproduce the problem

I think the above illustrates the steps needed to reproduce.

I believe the issue is here: https://github.com/clojure-emacs/orchard/blob/0768f8ed2be1b8d8f9dea185e72bdacc743c3a7c/src/orchard/cljs/meta.cljc#L90

In my example, `macro-namespace` is never called, so the code instead looks for the macro in `my-ns.core`, where it doesn't exist. I took the naive approach of simply swapping the two arguments to `or` and it seems to work for me. I can submit a pull request, but wanted to run it by you first to see if this solution even makes sense (I'm still fairly new to Clojure, and especially new to this codebase).

### Clojure version

1.10.0

### Java version

openjdk 11.0.10

### Operating system

Debian unstable

**Comment by bbatsov** [comment]
The suggested fix makes sense to me. I don't really remember why the code is written as it is, because I think we always submit the `context-ns`, which is what you've encountered. Perhaps @arichiardi can provide more input here. 

At any rate - PR welcome!

**Comment by arichiardi** [comment]
Fortunately we should have good tests there so we might as well try. The tricky part of that piece of code is exactly ordering...hopefully this will not be one of those case where it breaks.

**Comment by bbatsov** [comment]
I guess we didn't have a test for that particular problem, though. :-)

**Comment by arichiardi** [comment]
Maybe we should add one?

**Comment by arichiardi** [comment]
I will try to see if I can get back into this, this year was full for me 👶
