### ISSUE TITLE
cider-nrepl not working in guix due to jdk.javadoc.doclet not found

### ISSUE THREAD

**Issue by awb99** [clojure-emacs/orchard#117]
In gnu guix with Java OpenJDK installed via the packages  "openjdk"  "openjdk:doc"   "openjdk:jdk"
info and stacktrace causes this exceptions:

```
Caused by: java.lang.ClassNotFoundException: jdk.javadoc.doclet.Doclet
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
```

My cloure code stays the same. On fedora it is working, on guix it throws exceptions.

Is there a way to find out if javadoc is installed? Any pointer to what could be missing is appreciated!

## Expected behavior
:info and :stacktrace ops work

## Environment & Version information

guix with 

### Clojure version

latest stable

### Java version

from guix package 

### Operating system

linux

**Comment by awb99** [comment]
I solved the issue. In gnu guix the "openjdk" package removes javadoc libs, one has to use ONLY the package "openjdk:jdk".

**Comment by igajsin** [comment]
Hi, I've got the same problem as @awb99, but I don't get fully his solution. 
>  use ONLY the package "openjdk:jdk".
looks like a build-instruction. But I don't understand to build what? I don't build orchard intentionaly, just install cider via melpa and leiningen as a system package. Could you explain it for me?

**Comment by vemv** [comment]
Feel free to open an issue from scratch with a full stacktrace and context.
