### ISSUE TITLE
Tighten up the codecov.io data reporting

### ISSUE THREAD

**Issue by gonewest818** [clojure-emacs/orchard#12]
See https://github.com/clojure-emacs/cider-nrepl/issues/495 for details.

Same issues in this project.

**Comment by gonewest818** [comment]
Hey, passing along the information I received from codecov support:

Codecov support wrote:
> Hey Neil,
>
> This happens when the user we have on file loses authentication to the repository. Please fix by following these directions: http://docs.codecov.io/docs/team-bot
> 
> After you set the bot or add Github Integration please submit a new commit to CI so Codecov may use the new bot to interact with your repository.
> 
> Thank you!
> Steve

which means, a project maintainer needs to follow the link and do as it says...

**Comment by bbatsov** [comment]
I enabled the integration and it seems we're back in business. Thanks for looking into this!
