### ISSUE TITLE
AoT compiled function dependencies don't show up

### ISSUE THREAD

**Issue by Cyrik** [clojure-emacs/orchard#146]
```clojure
(fn-deps reverse)
;; => #{}
;; expected:
;; => #{#clojure.core/reduce1 #clojure.core/conj}
```

This is because the AoT code is not loaded by Clojures `DynamicClassLoader`. 
I've got a fix for some of this in a bit.
The harder problem is that some functions, like `map` inherit from `clojure.lang.RestFn` and do not have references to their dependencies. I'm still investigating if we can somehow cover those.

**Comment by vemv** [comment]
👍!

Probably querying the dependents of clojure.core functions isn't a frequent use case, so it seems a minor thing to worry about.

For AOTed code in general, other than the clojure core namespaces, having it at all it's an anti-pattern (AOT generally only belongs in prod) code so similarly it doesn't seem critical for us.

Of course, we'll be fine with cheap, incremental improvements, other than that probably we'd favor keeping things reasonably simple.

**Comment by Cyrik** [comment]
Makes sense. After looking at the byte-code it seems like there's no runtime way to do it anyway.
Relevant JVM bytecode for reverse:
```
  public static java.lang.Object invokeStatic(java.lang.Object);
    Code:
       0: getstatic     #15                 // Field const__1:Lclojure/lang/Var;
       3: invokevirtual #21                 // Method clojure/lang/Var.getRawRoot:()Ljava/lang/Object;
       6: getstatic     #27                 // Field clojure/lang/PersistentList.EMPTY:Lclojure/lang/PersistentList$EmptyList;
       9: aload_0
      10: aconst_null
      11: astore_0
      12: invokestatic  #32                 // Method clojure/core$reduce1.invokeStatic:(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
      15: areturn

public static {};
    Code:
       0: ldc           #40                 // String clojure.core
       2: ldc           #42                 // String conj
       4: invokestatic  #48                 // Method clojure/lang/RT.var:(Ljava/lang/String;Ljava/lang/String;)Lclojure/lang/Var;
       7: checkcast     #17                 // class clojure/lang/Var
      10: putstatic     #15                 // Field const__1:Lclojure/lang/Var;
      13: return
```

Here you can see that only conj is loaded from a var, reduce1 is called directly. Most other core bytecode is even worse and has no vars at all. It's sadly not just the RestFn stuff.
The only way to get at the reduce1 dependency is by deeply analyzing the byte-code which doesn't really fit the theme of orchard anyway.

It seems that any AoT compile code that calls functions marked with `:static` does not use vars for those functions. So basically 95% of core is out but most other AoT code should actually work.
