### ISSUE TITLE
parser.clj dies with unhelpful error messages in JREs without JDK

### ISSUE THREAD

**Issue by Archenoth** [clojure-emacs/orchard#157]
Heyas all!

It seems like there is this fun practice I've been noticing recently in Java-land of trimming out the Doclet classes in a some minimalist JDK distributions. This seems to break orchard, and render all of the tools that use it unusable on those platforms.

There was already an issue [with Guix specifically doing this a while ago](https://github.com/clojure-emacs/orchard/issues/152), but it turns out there are some places where you can't very easily install the rest of the trimmed-down JDK (or install a new one), such as the [IBM Semeru Runtimes](https://developer.ibm.com/languages/java/semeru-runtimes/) (and everything based on that) since they aren't installed with a package manager, and JDK classes aren't on maven. This means that there are several places that Clojure may be run where a large amount of its tooling is broken without any easy way to fix it

You can see these trimmed down versions of the JDK in the Semeru docker containers by running:
```sh
docker run -it --rm --network=host ibm-semeru-runtimes:open-17-jre
```

Installing Clojure normally:
```sh
curl -O https://download.clojure.org/install/linux-install-1.11.1.1113.sh
chmod +x linux-install-1.11.1.1113.sh
./linux-install-1.11.1.1113.sh
clojure
```

And then when inside you can try importing Doclet to see it missing:
```clojure
(import 'jdk.javadoc.doclet.Doclet)
```

Unfortunately, the existence of JDK versions in the wild without these classes appears to be growing--and I'm not sure how many other minimalist runtimes are ripping out stable and documented parts of the API, but I was wondering if it would be possible to check if these classes exist, and fail gracefully if not? That way the tools that rely on orchard could work in more of the places you might encounter Clojure code

I'm lucky, because I can just swap out our base runtime if I need to--but many others may not be, and while I know supporting implementations with quirks like this can be frustrating, I feel like accommodating the people on these platforms would be very much appreciated~

Thank you..!

**Comment by vemv** [comment]
Hi! Thanks much for the issue.

I'd say that Linux distros (unlike macOS) are subject to a conflation - server-centric requirements vs. dev-centric requirements. In macOS having dev-centric defaults is a pretty safe assumption since nobody is running servers on Macs.

Personally I think everyone's time is best spent in:

* finding out how to get a non-trimmed JDK for a particular distro
* Documenting so somewhere in the CIDER docs

i.e. any sort of 'graceful downgrade' in Orchard/CIDER would be counterproductive - any gains in reduced bug reports would translate to increased "why isn't feature _x_ working?" issue reports.

I'd say, if you are Linux, practically you _have_ to understand how JDK distros work, and that not every default is suitable for everyday development.

For instance, in our https://github.com/clojure-emacs/enrich-classpath project we found out that people may have to run `sudo apt install openjdk-11-source` (which installs `.java` sources for a given JDK). We don't plan to work around it - as mentioned, understanding one's distro is fairly crucial.

As a possibly obvious note, the JDK is OSS, it will never be the case that you cannot have a full installation.

And finally, I'd encourage anyone to create issues in the distros' issue trackers so that gets support / creates awareness, right where it belongs.

Hope it helps!

**Comment by Archenoth** [comment]
Yeah, that's fair! And I agree that documentation is a good place to help with this

I guess my main worry is the frequency that containerized environments won't have a JDK update path outside of completely subverting the container--and how it won't be obvious that Clojure tooling won't work until you actually need to use it, since typically development wouldn't happen on something so trimmed down. Meaning it would only be discovered after you discovered a fire in production and needed to do something about it

Maybe having a list of common Java distributions that orchard doesn't support could be helpful? Or maybe even just the stack trace in a searchable location with an explanation of what's happening? (`Syntax error compiling at (cider/nrepl/inlined_deps/orchard/v0v6v5/orchard/java/parser.clj:1:1)`)

Or maybe a giant scary warning saying that Doclet doesn't exist because the JDK they are using is incomplete and that things will probably break? (Like how nrepl does when you mismatch versions) Because I think it's pretty reasonable to expect that a runtime with stable APIs will have those APIs, and that burden really shouldn't have to fall on you

I just feel like the frequency that people run into this is going to grow as more things copy IBM and Guix, so having something to address this might be helpful

**Comment by vemv** [comment]
It's relevant to observe that while CIDER does work with containerized environments:

* they're less popular than installing a JDK in your host machine
* they tend to be bit of a second-class citizen; various CIDER features won't work as well as their rawer counterpart.

At least that's been my experience working in real-world teams over the years - first they try out the "containerize everything" route, but end up with a fundamentally simpler / more decoupled setup: JDK in the host machine, and stuff like databases etc in Docker.

It might be bit of a mindset shift for people coming from other languages (where "containerize everything" might work better), but adopting this decoupled setup might be also considered a rite of passage.

Even if using Docker containers, one can foster a sharp distinction between "development containers" (here: full JDK) and "production containers". I guess some people would object about dev-prod parity, but parity can be just a fancier word for "coupling", which us Clojurians don't really like :)

---

It's certainly possible to wrap our `import` in a try/catch, but I'd rather use the occasion for nudging people into doing the right thing, and documenting things better.

To be super clear, wrapping in try/catch would mean features would stop working. IME no `giant scary warning` would cut it - people would still ignore it and then ask why CIDER feature _x_ doesn't work.

For the time being, I'd just let time pass and see how things evolve for a variety of users. At least we now have a high-quality issue to point them out to. Thanks for that!

**Comment by Archenoth** [comment]
Oh my gosh. I'm so sorry, but turns out the PEBKAC levels were off the charts here

I was looking into the guix package to see if there were hints as to why it was packaged the way it was, and noticed that the trimmed down version was...just the JRE, like not actually JDK at all. So I went to compare it to what I had and noticed that the container that sent me down this rabbithole...I also failed to notice was *also* JRE (I literally pasted the jre container's name in the first post)

So uh, this error seems to happen when you run Orchard in the JRE (Though it's news to me that the Clojure compiler itself seems to work without JDK)

Could we get an error about that instead maybe? Since that seems like a much more in-scope problem, and would prevent people from being like me

**Comment by vemv** [comment]
😅

> Could we get an error about that instead maybe?

I don't know. Arbitrary things can break when using a JRE for dev purposes. It isn't any particular library's concern to detect that.

Personally I'd also put these under the 'rite of passage' category.

One simple actionable item would be to update our issue templates to state:

```md
## JDK

<!-- Please paste the exact JDK you are using here. JREs are not particularly supported. If you are on Linux, you may have to install the JDK sources separetely. -->

```

**Comment by Archenoth** [comment]
Agreed!

And honestly, I'm so embarrassed. I'm okay with closing the issue now that it's obvious what the cause was, and sorry for taking up your time (Though I'm gonna try to reflect my particular gotcha in the title a bit more specifically)

**Comment by vemv** [comment]
No issue! I've created https://github.com/clojure-emacs/cider/pull/3196
