### ISSUE TITLE
error reporting fails when project contains invalid namespace declaration

### ISSUE THREAD

**Issue by mk** [clojure-emacs/orchard#158]
## Expected behavior
I expect orchard `orchard.namespace/classpath-namespaces` to be resilient to faulty ns declarations.

## Actual behavior
The precence of a faulty ns declaration on the class path like `(ns (:requires [clojure.string]))` causes nrepl to swallow the error and just print an exception to the REPL output.

## Steps to reproduce the problem

``` 
git clone https://gist.github.com/mk/bd82092048d733ef3de0e312898f47b4 nrepl-issue
```

Open the project and run `cider-jack-in`

Try evaluating any expression that throws an expression (there's one in foo.clj).

### Clojure version
1.11.1

### Java version
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.2.0-dev (build 17.0.3+4-jvmci-22.1-b03)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0-dev (build 17.0.3+4-jvmci-22.1-b03, mixed mode, sharing)

### Operating system
macOS Monterey

I'll follow up with a PR shortly.

**Comment by vemv** [comment]
@mk : could you please enable `Allow edits by maintainers` in your fork?
