### ISSUE TITLE
Remove javadoc fallback

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/orchard#160]
https://github.com/clojure-emacs/orchard/blob/c0e24f71292f4fed8d4d8cf854a99e4a80cf6ee6/src/orchard/java.clj#L385

`11` isn't a special JDK and defaulting to it can mask issues (especially as we complete and enable enrich-classpath)

**Comment by bbatsov** [comment]
Isn't this unrelated to to what `enrich-classpath` does? It simply computes the URL for the remote JavaDoc. I think 11 was the newest LTS when this was written, that's why it was the default.

**Comment by vemv** [comment]
But 11 (or any single choice) isn't accurate, also can lack results for the newer classes that can get added for each JDK.

When enrich-classpath gets its finishing touch I'd feel more comfortable tweaking this section of code.

**Comment by bbatsov** [comment]
Yeah, that's fair. Frankly, I'm not sure in which case `java-api-version` might return `nil` to begin with. I guess this fallback simply guards against this case.

**Comment by alexander-yakushev** [comment]
This was addressed in https://github.com/clojure-emacs/orchard/commit/bb22fb37938087ebf40880cd1322e0ad93b79126, right?

**Comment by vemv** [comment]
SGTM. We don't give a lot of uses to javadoc anyway

https://github.com/clojure-emacs/cider/issues/3575
