### ISSUE TITLE
Remove internal cache atoms

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/orchard#186]
We have some atoms, for caching.

It's likely better to leave things slower (for now) so that we don't favor OOMs.

See https://chat.openai.com/share/3069aebe-87ad-4354-a839-5c29f864f9e2

**Comment by bbatsov** [comment]
Depends on how likely those OOMs are. I'm guessing the bulk of the users never experience them, given that I've rarely seen such reports.

**Comment by vemv** [comment]
They support features that are only visible when using enrich-classpath, so most people haven't exercised those code paths a lot.

There's already some caution around memory, e.g. https://github.com/clojure-emacs/orchard/blob/c1ce92703f11c69229c90d70c95fee9e9ddabb61/src/orchard/java.clj#L262-L270
