### ISSUE TITLE
Add MrAnderson to the project

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/orchard#2]
Basically we need to obfuscate orchard's deps, so they wouldn't conflict with the deps of projects that are using it (we can't obfuscate only `dynapath`). 

It'd be nice if we can do this obfuscation automatically on TravisCI. //cc @gonewest818

**Comment by SevereOverfl0w** [comment]
Shouldn't it be cider-nrepl that runs Mr. Anderson against orchard? That would allow multiple versions of orchard to be loaded then.

I'm presuming that Mr. Anderson works transitively when I say this. I'd be surprised if it didn't though!

**Comment by bbatsov** [comment]
Yeah, it certainly does. I was just thinking of this being used by people like @volrath. I'm fine with not using `MrAnderson` at this level, I just recall there were some issues dynapath and MrAnderson.

**Comment by gonewest818** [comment]
fyi - I just sent a PR with the general Travis CI setup for orchard, but I didn't do anything about MrAnderson.

**Comment by bbatsov** [comment]
After some thinking I've decided it's best to just leave this step for `cider-nrepl` and other client libraries. 

Btw, @gonewest818 I was wondering if you know how to setup some auto-publishing of snapshots to Travis. I find it very annoying that I manually have to push each update. Probably the only real problem is how to stuff some credentials securely in the build step. Would be nice for both `orchard` and `cider-nrepl` if possible and would get rid of the common problem of forgetting to push some new snapshot release.

**Comment by gonewest818** [comment]
Yes - I’ve done auto-publishing to clojars as an experiment, but I haven’t looked at it in a while. Let me go refresh my memory how that was set up. If there’s no separate ticket for this I’ll create one.

**Comment by bbatsov** [comment]
👍 I guess I can close this ticket.

**Comment by devth** [comment]
This might be the wrong place but only thing I could find googling for this warning I'm seeing on java 11 clojure 1.10 lein 2.9.1:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by mranderson049.orchard.v0v4v0.dynapath.v0v2v5.dynapat
h.defaults$eval39837$fn__39838 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of mranderson049.orchard.v0v4v0
.dynapath.v0v2v5.dynapath.defaults$eval39837$fn__39838
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access
 operations
WARNING: All illegal access operations will be denied in a future release
```

Is there a fix?

**Comment by bbatsov** [comment]
See #20
