### ISSUE TITLE
Inspector: datafy is rendered for maps with nil values

### ISSUE THREAD

**Issue by alexander-yakushev** [clojure-emacs/orchard#206]
The inspector has a guard in place to avoid rendering datafied representation if it the same as the plain view of the object. However, this causes plain maps to be rendered twice if the map contains at least one `nil` value. Example:

<img width="352" alt="image" src="https://github.com/clojure-emacs/orchard/assets/468477/a6352ea1-47bd-4531-a551-b2b0999b27c7">

Is this an expected behavior?

**Comment by vemv** [comment]
This was fixed in https://github.com/clojure-emacs/orchard/pull/200

I should cut a release around today 👀

**Comment by alexander-yakushev** [comment]
My bad, sorry!

**Comment by vemv** [comment]
No issue!

I just cut new orchard + cider-nrepl versions, as available in cider master.
