### ISSUE TITLE
Next/previous sibling functions - refinements

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/orchard#232]
Hi @p4v4n , I checked out the recent changes. While it's an improvement over how things were before, there's still some room for refinements.

Let's assume an Inspector object with two pages.

* In page 1, next-sibling on the last item should get me to the first element of the page 2
  *  (curently: does nothing)
* On page 2, previous-sibling on the first item should get me to the last element of the page 1
  * (currently: fails by returning nil instead of the current inspector)

Overall, I find that the correct behavior is that by using next/previous sibling, the user should be able to go smoothly from the first element of the first page to the last element of the last page, no matter how many pages are there in between.

It should also work in the opposite direction (last item of last page to first item of first page).

Normally, if we try to get past boundaries, we should re-render the same inspector instead of returning nil.

The current state of things can be tried in cider master / cider-nrepl latest.

Cheers - V

**Comment by vemv** [comment]
Thanks @p4v4n ! It's no issue and the current state is an acceptable intermediate one.

Would look forward to a PR anytime

**Comment by p4v4n** [comment]
Just a small update. 
I tried the latest cider and cider-nrepl and tried the latest code and `previous-sibling` works fine for me across all pages.

Steps I tried to reproduce:
1. Inspect (range 100) 2. Go to page 4 3. Go down into any element 4. Press '9' 100 times.

It goes back to 0 and stops as expected.

**Comment by vemv** [comment]
Tried out quickly - you're right!
