### ISSUE TITLE
Boot support EOL?

### ISSUE THREAD

**Issue by alexander-yakushev** [clojure-emacs/orchard#259]
I know I've been one of Boot power users in the past, but given how it's completely stale now, the question on the table is how long CIDER continues to support it. The cost of supporting is little (a couple of hacks in Orchard), but we don't even verify that those hacks still work. What would be the conditions to drop it?

[State of Clojure 2023](https://www.surveymonkey.com/stories/SM-_2BH3b49f_2FXEkUlrb_2BJSThxg_3D_3D/) lists Boot usage at <1%.

Not trying to push EOL forward, only gauging the sentiment.

**Comment by vemv** [comment]
I think that in some or other discussion we all observed that it's fine to nuke from code and docs.

It's not in https://github.com/clojure-emacs/cider/issues/3356 although I'm sure it's uncontroversial.

**Comment by bbatsov** [comment]
Yeah, Boot support should be removed as the project has been dead for several years now. I can’t remember the last time any user mentioned Boot. And it was probably you back then! 😂

**Comment by bbatsov** [comment]
I think we can close this, as the special support for Boot's classloader was already removed in #285.
