### ISSUE TITLE
Inspector - more compact delimiters

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/orchard#264]
I don't remember if this was always the case, but as of master I see ` ) ) ) ] ] ] ] ]` sequences that take some valuable real estate:

![image](https://github.com/clojure-emacs/orchard/assets/1162994/5071526a-5e61-4a4a-b31f-dd5cdfc4511d)

(Perhaps this wasn't changed directly, but its a consequence of the improved deep printing)

I'd suggest having a `:compact` option or so.

Thoughts? @alexander-yakushev

**Comment by alexander-yakushev** [comment]
Yes, it always was exactly like this, so I reproduced this behavior in the new printer. I'm not sure why this particular look has been chosen.

The rendered code looks especially awful here. Everything else has a bit more "breathing room", I suppose. Anyway, no other printer in Clojure uses this kind of formatting, and CIDER uses normal format in other places for rendering values (debugger, enlighten), so I had to support both in `orchard.print`. 

I don't find much value in using a unique format in the inspector. We can slash that and have the same view everywhere.

**Comment by vemv** [comment]
I'd be OK with the slashing because the Inspector printing has always been sort of broken (or at least messy) in misc ways.

Users are always encouraged to further drill down anyway.

**Comment by alexander-yakushev** [comment]
Given that the support for both kinds of printing is already implemented, let's first make the compact one the default, with the ability to switch it, and see if anybody asks/complains.

**Comment by vemv** [comment]
Also SGTM!

**Comment by vemv** [comment]
0.25.0 has been tagged
