### ISSUE TITLE
Decided what to do with Cloverage for CI

### ISSUE THREAD

**Issue by shen-tian** [clojure-emacs/orchard#45]
Currently, the cloverage job is skipped on CircleCI, as it's been failing for the last while. The thinking is that let's rather be used to the build going green, as to avoid a broken window effect.

However, we should probably either fix that job, or abandon the capability (too much effort for not enough gain).

**Comment by bbatsov** [comment]
I'd probably just drop it. I don't think cloverage ever worked reliably (at least for me), so for me it seems like just a waste of our time.

**Comment by vemv** [comment]
Hope Cloverage can serve us better in a future, it has bit of a backlog that should be addressed first.
