### ISSUE TITLE
Ensure CI image includes JDK sources and tools 

### ISSUE THREAD

**Issue by jeffvalk** [clojure-emacs/orchard#50]
To run all tests, the CI Docker image needs to include:

1. `src.zip` for all JDKs; and
2. `tools.jar` for JDK8.

Both of these should be located either in the JDK root, or in the `lib` directory under this.

**Comment by shen-tian** [comment]
There's a growing list of reason to look beyond the CircleCI convenience images for Clojure. I'd be up for having a go at that from mid may or so, and that should address this. But anyone else who can get to this before then, please do :)

**Comment by bbatsov** [comment]
Btw, an user just reported on Slack that with the current Orchard snapshot he's getting:

```
Syntax error compiling at (cider/nrepl/inlined_deps/orchard/v0v5v0_beta2/orchard/java/legacy_parser.clj:1:1).
...
Caused by: java.lang.ClassNotFoundException: com.sun.javadoc.ClassDoc
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at clojure.lang.RT.classForName(RT.java:2211)
    at clojure.lang.RT.classForNameNonLoading(RT.java:2224)
    at cider.nrepl.inlined_deps.orchard.v0v5v0_beta2.orchard.java.legac...
```

I assume the reason is the same and I'll relay the solution, but I think we should try to fail more gracefully in such cases.

**Comment by jeffvalk** [comment]
If the user could confirm or refute the hypothesis that this is caused by a bad file on the classpath, that would be helpful.

**Comment by bbatsov** [comment]
Btw, this error is also on the cider-nrepl builds now https://circleci.com/gh/clojure-emacs/cider-nrepl/151

**Comment by bbatsov** [comment]
And this has also cascaded to cljdoc https://circleci.com/gh/cljdoc/builder/4505 :-)

**Comment by jeffvalk** [comment]
Presumably the same image is used for the CI container in all of those cases. Seeing what's in that sounds like the place to start.

**Comment by bbatsov** [comment]
Yeah, you're probably right. I'm mostly concerned that end users started reporting problems. Before the changes I don't recall anyone getting exceptions on JDK 8. As the parser is more or less the same on JDK 8 as it was before I wonder what caused this change in behavior for them.

**Comment by jeffvalk** [comment]
> the parser is more or less the same on JDK 8 as it was before

The parser is. But as of fabb9b07f41cb4d2229cf1519b69b55e75b1e7c0, the code that loads the parser now searches for `tools.jar` in more locations. Orchard may have started finding that file on the CI image, but as a broken link or without read permissions, etc.

>  I'm mostly concerned that end users started reporting problems.

Me too. I'd like to prevent the error, but the only way I've found to reproduce it is having a `tools.jar` file present, but be invalid. If someone renames a cat gif to `tools.jar`, I'm not sure orchard can save them. :-)

Any idea how look at the file system of the Docker image being used?

**Comment by pepperblue** [comment]
I don't know, if that helps ...
Have this problem on two different systems: Debian-based SolydK and Arch.
If I use openjdk-8 from package-management-system, `tools.jar` is not on the classpath. If I use openjdk-8 from `adoptopenjdk.net` - both jvm-versions work - on SolydK / `java-8-j9` from AUR on Arch nrepl works ...
I tried copying `tools.jar` from  java-8-j9 to java-8-openjdk on Arch to ensure having a valid `tools.jar`, but it did not help ...

**Comment by jeffvalk** [comment]
@pepperblue When you see this error, what are:
1. The file path of `tools.jar`; and
2. The value of `(System/getProperty "java.home")`?

**Comment by pepperblue** [comment]
@jeffvalk In which context should I eval `(System/getProperty "java.home")`?
If I try it in Spacemacs with `M-:` I get `Lisp error: (void-function System/getProperty)`

**Comment by bbatsov** [comment]
@pepperblue You should eval this in a CIDER REPL or using CIDER's `C-c M-:`.

**Comment by pepperblue** [comment]
@bbatsov I'm not able to get a not working REPL to eval `(System/getProperty "java.home")`

**Comment by bbatsov** [comment]
Not even something like `clj`? (it doesn't have to be in Emacs)

**Comment by pepperblue** [comment]
@bbatsov With cider I get a clj-prompt but when I try to eval:

![error](https://user-images.githubusercontent.com/3543271/57179703-cfa3d280-6e80-11e9-9845-207d4f78e7bd.png)

Not using cider, I can get a working REPL with:
`(System/getProperty "java.home")` = "/usr/lib/jvm/java-8-openjdk/jre"
and path to `tools.jar` = "/usr/lib/jvm/java-8-openjdk/lib/tools.jar"

And for the working case:

![working](https://user-images.githubusercontent.com/3543271/57179906-72f5e700-6e83-11e9-871c-71e3277c7a62.png)

lein-repl:
`(System/getProperty "java.home")` = "/usr/lib/jvm/java-8-j9/jre"
and path to `tools.jar` = "/usr/lib/jvm/java-8-j9/lib/tools.jar"

**Comment by jeffvalk** [comment]
@pepperblue The paths from `lein repl` help.

Could you confirm that `/usr/lib/jvm/java-8-j9/lib/tools.jar`:

1. Is a readable jar file that contains the file entry `/com/sun/javadoc/ClassDoc.class`, and
2. Is the file that is part of the JDK8 package (i.e. you haven't changed this file, or moved it from another JDK)?

**Comment by jeffvalk** [comment]
@respatialized Since you've experience this too, the following info would be helpful and appreciated:

1. The value of `(System/getProperty "java.home")`? (Use `lein repl` without CIDER to check.)
1. The file path of `tools.jar`
1. Whether that `tools.jar` file is
    1. a readable jar file that contains the jar entry `/com/sun/javadoc/ClassDoc.class`
    1. the file that is part of the installed JDK8 package (i.e. you haven't changed this file, or moved it from another JDK)?

For context, the only way I've been able to reproduce this issue so far, is to have `tools.jar` be a bad file (empty file, errant symlink, unreadable permissions, etc). If something else can trigger this, it would be very helpful to know.

**Comment by pepperblue** [comment]
> @pepperblue The paths from `lein repl` help.
> 
> Could you confirm that `/usr/lib/jvm/java-8-j9/lib/tools.jar`:
> 
>     1. Is a readable jar file that contains the file entry `/com/sun/javadoc/ClassDoc.class`, and
> 
>     2. Is the file that is part of the JDK8 package (i.e. you haven't changed this file, or moved it from another JDK)?

I can confirm that both `tools.jar` files
- belong to their packages (I uninstalled and installed `java-8-openjdk` to ensure this)
- are readable `rw-r--r--`
- contain `/com/sun/javadoc/ClassDoc.class`

For clarity: `java-8-j9` is the java-version that is working for me ...

**Comment by jeffvalk** [comment]
@pepperblue 

> java-8-j9 is the java-version that is working for me

We're interested in the JDK8 instance that *does* produce this error. In your case, it sounds like we need the information I mentioned above for `/usr/lib/jvm/java-8-openjdk/lib/tools.jar`. Could you share this?

**Comment by respatialized** [comment]
@jeffvalk Thanks for the direction.

1. My openJDK `/usr/lib/jvm/java-8-openjdk-amd64/`
2. `tools.jar` is in `/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar` 
3. I opened `tools.jar` in an emacs buffer and confirmed that `/com/sun/javadoc/ClassDoc.class` is present.

I just found `tools.jar` by looking in the java dir - is there a way of checking from lein or clojure that this is the jar used at runtime?

Also, perhaps this might be relevant: when I was trying random things to try and see what might fix the error, I tried to check which JDK I was running by calling `java --version` - and it threw a fatal error when trying to initialize the JVM. But clearly _some_ JVM works, because `lein repl` in the projects works just fine. Figured it was worth mentioning, at least.

**Comment by jeffvalk** [comment]
@respatialized

> s there a way of checking from lein or clojure that this is the jar used at runtime?

Yes, and good idea to check. Run the following in `lein repl` and let me know what you get. (This is the path search `orchard.java` does internally.)

```clj
(require '[clojure.java.io :as io])
(let [f "tools.jar"
      home (io/file (System/getProperty "java.home"))
      parent (.getParentFile home)
      paths [(io/file home f)
             (io/file home "lib" f)
             (io/file parent f)
             (io/file parent "lib" f)]]
  (->> paths (filter #(.canRead %)) first io/as-url))
```

> Also, perhaps this might be relevant: when I was trying random things to try and see what might fix the error, I tried to check which JDK I was running by calling java --version - and it threw a fatal error when trying to initialize the JVM. But clearly some JVM works, because lein repl in the projects works just fine. Figured it was worth mentioning, at least.

Good info, thanks. Two observations:

1. `java --version` has an extra dash in the option; it's actually `-version`. Not sure if that was the problem there.
1. The fact that some JDK8 configuration works for you (and @pepperblue), but another does not is the information we need to solve this one. Do you have more than one JDK installed? If so, do you have more than one JDK8 instance?

**Comment by respatialized** [comment]
Calling that function yields the same path - `#object[java.net.URL 0x1e48e9e6 "file:/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar"]`. 

The single dash works and points to `openjdk version "1.8.0_191"`. Thanks for clarifying that! I do have OpenJDK11 installed (also at `/usr/lib/jvm`). I've never attempted to install a second JDK8, as far as I know.

What may be more interesting here, however is that there's another folder in that path, `java-1.8.0-openjdk-amd64`, which is symlinked to the other path, `java-8-openjdk-amd64`.

**Comment by pepperblue** [comment]
> @pepperblue
> 
> > java-8-j9 is the java-version that is working for me
> 
> We're interested in the JDK8 instance that _does_ produce this error. In your case, it sounds like we need the information I mentioned above for `/usr/lib/jvm/java-8-openjdk/lib/tools.jar`. Could you share this?

For that reason I confirmed things for **both** versions of `tools.jar`. Will say `tools.jar` from the working **and** the not-working instance
- belong to their packages
- are readable rw-r--r--
- contain /com/sun/javadoc/ClassDoc.class

Checking which `tools.jar` is used at runtime I get:
`#object[java.net.URL 0x6ce61c0b "file:/usr/lib/jvm/java-8-openjdk/lib/tools.jar"]`

**Comment by jeffvalk** [comment]
I believe the `ClassNotFoundException` is fixed in 314c84a842d24d3a5b70c7e869247475b1b13231. It appeared as though, in come cases, loading `tools.jar` succeeded, but the classloader used wasn't high enough in the hierarchy to ensure the classes were visible. I've never been able to reproduce the issue locally, but tests are passing on the CI server now.

**Comment by pepperblue** [comment]
How can I get my Spacemacs-Installation to use a cider version that's including this commit?

**Comment by bbatsov** [comment]
I'll cut a new beta release now and a new `cider-nrepl` snapshot.

**Comment by pepperblue** [comment]
Cider-nrepl is working again with both instances of jdk8 on my Arch-system :-)
Will check the Debian-based-system on Thursday ...
Thank you for fixing this rapidly!

**Comment by jeffvalk** [comment]
Thanks @pepperblue and @respatialized for sharing the detail! Without that, it wouldn't have been simple to chase this one down.
