### ISSUE TITLE
Kafka documentation

### ISSUE THREAD

**Issue by AndreaCrotti** [clojure-emacs/orchard#62]
Use the template below when reporting bugs. Please, make sure that
you're running the latest stable release or the latest snapshot of
`orchard` and that the problem you're reporting hasn't been
reported (and potentially fixed) already.

## Expected behavior
When doing `cider-javadoc` on a Kafka method, it should go to the right API version.

## Actual behavior

At the moment it goes to `https://kafka.apache.org/090/javadoc/index.html` which gives a 404.

It's easy to see why, from these lines in master:
```
;; TODO: Seems those were hardcoded here accidentally - we should
;; probably provide a simple API to register remote JavaDocs.
(javadoc/add-remote-javadoc "com.amazonaws." "http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/")
(javadoc/add-remote-javadoc "org.apache.kafka." "https://kafka.apache.org/090/javadoc/index.html?")
```

Would be great to jump to the right API version, but if that's too hard we could maybe update it to the latest stable API?

**Comment by AndreaCrotti** [comment]
Sadly I can't see a working `latest` url for kafka docs, which at least would help partially.

**Comment by bbatsov** [comment]
> When doing cider-javadoc on a Kafka method, it should go to the right API version.

One more reason not to hardcode those URLs. :-) I guess we should have the users add such extra URLs via their CIDER config or something like this. Then you can easily add the right JavaDoc URL for your Kafka version.

**Comment by vemv** [comment]
Orchard does not currently add javadocs in its `src`.

Javadoc-fetching functionality is provided by https://github.com/clojure-emacs/enrich-classpath which is enabled by default in CIDER (for Lein) these days.

**Comment by bbatsov** [comment]
Did we document that people should do this themselves now:

```
(javadoc/add-remote-javadoc "com.amazonaws." "http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/")
(javadoc/add-remote-javadoc "org.apache.kafka." "https://kafka.apache.org/090/javadoc/index.html?")
```

(for Javadoc lookup commands to work)
