### ISSUE TITLE
Move ClojureScript dep to profiles

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/orchard#65]
Run now we've hardcoded the dep, which is bad for end users. It should go to all profiles the way we've done for other projects (e.g. https://github.com/clojure-emacs/cider-nrepl/blob/master/project.clj). 

@arichiardi The current code will work with older ClojureScript releases, right?

**Comment by SevereOverfl0w** [comment]
I don't know the state of the code, but can we ensure that all the code works without cljs loaded, lest we end up with the same problem we have at piggieback.

**Comment by bbatsov** [comment]
Well, that would be ideal, but it might be a bit harder here. When I agreed to baking the ClojureScript support in Orchard I didn't now many deps ClojureScript was pulling in (I assumed it didn't have any runtime deps). While that's not an issue for `cider-nrepl`, which obfuscates the deps, it will be an issue for everyone using `orchard` directly.

**Comment by SevereOverfl0w** [comment]
The clojurescript dependency cannot be obfuscated. Otherwise you won't be accessing the right clojurescript state (via the compiler env)

**Comment by bbatsov** [comment]
Ah, yeah. Silly me. Well, I guess we'll figure something out.

**Comment by SevereOverfl0w** [comment]
Piggieback solved this with a "shim" to only load cljs code when cljs was available.
