### ISSUE TITLE
Fix README typo

### ISSUE THREAD

**Issue by webappzero** [clojure-emacs/orchard#67]
I noticed a potential typo in the README. Or maybe I'm not reading the intent correctly.

**Presently it reads:**

> API Optimized for Editors
> 
> Code editors can't know what symbols resolve to without consulting a REPL that's why they would typically send a combination of a symbol name and some ns (e.g. the current namespace), so they **can't** be resolved to some var on which an operation would be invoked.

**But I expected to read can instead of can't. The suspect word is bolded above and below:**

> API Optimized for Editors
> 
> Code editors can't know what symbols resolve to without consulting a REPL that's why they would typically send a combination of a symbol name and some ns (e.g. the current namespace), so they **can** be resolved to some var on which an operation would be invoked.

**Comment by bbatsov** [comment]
Good catch! I'll address this soon.
