### ISSUE TITLE
orchard.query/namespaces fails when there's a syntax error

### ISSUE THREAD

**Issue by SevereOverfl0w** [clojure-emacs/orchard#70]
You get a NPE on the call to `inlined-dependency?`. This is because load-project-ns returns namespaces that have failed to load, so `find-ns` is unable to find it.

If we can determine the correct behavior, this would make a good first issue.

**Comment by bbatsov** [comment]
Can you expand on this with some example?

**Comment by vemv** [comment]
Couldn't repro as we now have these `filter` guards:

https://github.com/clojure-emacs/orchard/blob/63c580038b208b66e1f7df24345058a8d5663359/src/orchard/namespace.clj#L109-L111
