### ISSUE TITLE
Handle lack of internet connectivity when the ClojureDocs cache is missing

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/orchard#71]
A couple of people have experienced problems trying to use `cider-nrepl` when not connected to the internet or behind a corporate firewall, because the download of the ClojureDocs export locks up. We should figure out some solution to this. Some options:

* Do the download in the background
* Try to detect if we have access to the remote host
* Ship some fallback data with orchard

@liquidz Any thoughts on this?

**Comment by liquidz** [comment]
@bbatsov 

> Try to detect if we have access to the remote host

I think this option is good.

> Do the download in the background

With this option, there is a status management during downloading, so codes seems to be complicated.

> Ship some fallback data with orchard

It looks good, but it seems to be painful to update fallback data regularly.
It may be possible to adopt it once and consider the automatic update method later.
BTW I think detecting remote host access will be necessary to fallback after all.

**Comment by bbatsov** [comment]
I don't have a strong preference for how to solve this, I just want us to come up with something that avoids the lock ups.

**Comment by liquidz** [comment]
@bbatsov
OK. I'll try to fix it this weekend!

**Comment by bbatsov** [comment]
Thanks!

**Comment by SevereOverfl0w** [comment]
We should perhaps think about tethered internet case also:

1. Slow
2. Expensive

**Comment by bbatsov** [comment]
Is there even a way to detect this programatically?

**Comment by bbatsov** [comment]
Fixed in #72.
