### ISSUE TITLE
info fails to find the file when it lacks any `def`s.

### ISSUE THREAD

**Issue by PEZ** [clojure-emacs/orchard#75]
If I have a file `foo.clj` without any `def`s in it. For instance if it has only this content

```clojure
(ns foo)
```

And then ask for `info` on it. I get no `:file` path in the response.

But if I have this:

```clojure
(ns foo)

(def foo 42)
```

Then I get the `:file` path for this file in the response.

## Steps to reproduce the problem

I'm not sure how to reproduce this in any other way than creating the files in a Clojure project:

`foo.clj` with contents:
```clojure
(ns foo)
```

`bar.clj` with contents
```clojure
(ns bar
  (:require foo))
```

Then I load `bar.clj` and use my favorite nREPL tool, Calva, to peek at the definion of `foo` (<kbd>alt</kbd>+<kbd>F12</kbd>). Calva shows an info hover saying ”No definition found for foo”.

Then If I add `(def foo 42)` to `foo.clj`, I can peek at the definition from `bar.clj`.

### Clojure version

1.10.0

### Java version

1.12

### Operating system

MacOS Mojave

**Comment by bbatsov** [comment]
Fixed by #76.
