### ISSUE TITLE
cljdoc is failing to compile

### ISSUE THREAD

**Issue by mauricioszabo** [clojure-emacs/orchard#90]
The latest (and some older versions) of the documentation is now showing - it's just showing `API import failed in build  #28834`, and it points to https://cljdoc.org/builds/28834

Is it something easy to fix? Or is there any way to build the documentation locally, so we can explore the API?

**Comment by bbatsov** [comment]
The docs fail to compile because cljdoc doesn't work with Java 9+ :( . See my comment on this ticket https://github.com/cljdoc/cljdoc/issues/275

**Comment by boxxxie** [comment]
Is there any working documentation that you guys can point me to? or maybe add a section on the README for how to build the docs myself.

**Comment by vemv** [comment]
We'll see whether it worked with the next release on Clojars
