### ISSUE TITLE
Java unresolved symbols should not return info 

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/orchard#92]
From a comment on Slack, I decided to open an issue so that we can track it.

> I just noticed Cider is returning Java member docs and eldoc for unresolved symbols without a period, eg. (shift |) being interpreted as java.lang.StringBuffer/shift

## Expected behavior

It should not return an entry.

## Actual behavior

It seems it does, will double check.

**Comment by arichiardi** [comment]
This seems to be an expected behavior, even if it sounds to me a bit odd indeed.

There is even a test for it.

https://github.com/clojure-emacs/orchard/blob/master/test/orchard/java_test.clj#L359-L361

Maybe @bbatsov you know better than me why this is desirable?

**Comment by arichiardi** [comment]
Can it be for eldoc on the `..` forms? 

If that is the case we might need to cope with the fact that those "unresolved" symbols the user was talking about are actually part of the namespace, always loaded cause of `java.lang` and they will always show up

**Comment by vemv** [comment]
> Can it be for eldoc on the `..` forms?

Yes, dots are removed eldoc-side:

https://github.com/clojure-emacs/cider/blob/318fe6878d8bedf5db9dfa649dedb45d72b2e7ee/cider-eldoc.el#L432

So that limitation of our eldoc impl unfortunately dictacted Orchard's API.

Ideally cider-eldoc would detect whether a `..` form is being parsed, and communicate that as part of the request to cider-nrepl.

**Comment by vemv** [comment]
Probably we shouldn't change the current api since it would constitute a breaking change.

We can add a new one however. Which should be driven by a specific need - I'd suggest we close the issue in the meantime
