### ISSUE TITLE
Make test-watch does not work anymore

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/orchard#94]
Hi there I am putting this here as reminder and ask for help :smile: 

## Expected behavior

I expected `make test-watch` which is basically just an alias for `test-refresh` would work. I found it very useful for the `info` tests but we might want to delete it if we cannot find a solution. 

## Actual behavior

It does not work and the workaround seems to completely comment out the namespace together with [this line](https://github.com/arichiardi/orchard/blob/fix-86-2/src/orchard/java.clj#L117).

My guess is that `test-refresh` *always* tries to load `orchard.java.legacy-parser` which is dynamically loaded otherwise and depends on the JDK. Not too sure if there is another fix cause I haven't paid too much attention to the JDK doc PRs :smile: 

## Steps to reproduce the problem

`make test-watch` 

### Clojure version

any

### Java version

- Not too sure, I haven't had the time to try it -

**Comment by bbatsov** [comment]
Yeah, supporting JDK8 and 9+ definitely causes a lot of pain, but there's not much we can do right now. I guess it will be a very long time until people abandon JDK8.

**Comment by bbatsov** [comment]
P.S. These days we should probably adopt kaocha as our test runner.

**Comment by vemv** [comment]
We ended up removing `test-refresh` from a couple clojure-emacs projects, because they can as well be setup in one's profiles.clj or such.

Same for other plugins like humane-test-output etc, that one was particularly obstrusive.

**Comment by arichiardi** [comment]
Agree about kaocha, it encapsulates all of the other plugins, thanks a lot for tanking a look at it!
