### ISSUE TITLE
Syntax error occured with nREPL 0.8.0 and cider-nrepl on Java8

### ISSUE THREAD

**Issue by liquidz** [clojure-emacs/orchard#98]
## Expected behavior

`lein repl` will launch.

## Actual behavior

```
ERROR: Unhandled REPL handler exception processing message {:code (clojure.core/binding [clojure.core/*ns* (clojure.core/or (clojure.core/find-ns (clojure.core/symbol "reply.eval-mode
s.nrepl")) clojure.core/*ns*)] (set! *print-length* nil)), :id d9e84203-70ce-4144-8d6c-8c8aa8994446, :op eval, :session 71e6dc37-2c17-48a9-b70e-b42454c30d3d}
Syntax error compiling at (cider/nrepl/inlined_deps/orchard/v0v6v0/orchard/java/legacy_parser.clj:1:1).
```

Full error messages are here
https://gist.github.com/liquidz/6c2da4394b3a238947ad493c604e0d7a

## Steps to reproduce the problem

- create project
```sh
docker run --rm -it clojure:openjdk-8-lein bash
lein new foo
cd foo
```
- edit `project.clj`
```clojure
(defproject foo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [nrepl "0.8.0"]]
  :plugins [[cider/cider-nrepl "0.25.3"]]
  :repl-options {:init-ns foo.core})
```
- run `lein repl`

### Clojure version

- 1.10.1

### Java version

- 1.8

### Operating system

- Debian (Docker image: clojure:openjdk-8-lein)
- macOS Catalina

**Comment by bbatsov** [comment]
The root of the error is some missing class in the JDK, right?

I think I saw a few reports of this problem recently, but I was unable to reproduce them. The big mystery for me is that nothing has been changed in the legacy parser for quite a while and I'm surprised by this weird interaction with the new nREPL. @shen-tian Perhaps that's somehow related to the dynamic middleware loading changes?

**Comment by bbatsov** [comment]
Those issues seem related to me:

- https://github.com/clojure-emacs/cider/issues/2872
- https://github.com/clojure-emacs/cider/issues/2863

I just didn't think they might be related to nREPL 0.8.

**Comment by SevereOverfl0w** [comment]
I wonder if some jvms don't have all of the doclet classes. Maybe it's only a jre?

**Comment by bbatsov** [comment]
@SevereOverfl0w It seems @liquidz used a docker container with a JDK.

**Comment by bbatsov** [comment]
Actually I can reproduce the problem now - in the past I was just doing cider-jack-in, but it occurred to me that the problem is probably something specific to using REPLy. Still, I have absolutely no idea what causes it.

**Comment by liquidz** [comment]
Thanks for your confirmation!
I have no errors with nREPL 0.7, so I assumed  it was a 0.8 issue.

> it occurred to me that the problem is probably something specific to using REPLy. 

Oh, I confirmed tools.deps give me no errors.

**Comment by liquidz** [comment]
@bbatsov Could these changes be the cause?
https://github.com/nrepl/nrepl/commit/c3ec4c6#diff-1b9ca3ef5a3a453d96b5f6c1b8c778a5L73-L138

When I revert these changes, there seems to be no errors.

**Comment by bbatsov** [comment]
Probably you're right. I suspected it must be something to do with classloaders. Might be best to move this to nREPL's issue tracker and ask @shen-tian if he has time to investigate this.

**Comment by liquidz** [comment]
OK. I'll move this issue. Thanks!
